@startuml
title DeletePetCommand Sequence Diagram

participant ":CuddleCare" as CuddleCare
participant ":DeletePetCommand" as DeletePetCommand
participant ":PetList" as PetList
participant "<<class>>\nUi" as Ui

activate CuddleCare

' Constructor
CuddleCare -> DeletePetCommand** : new(petList)
activate DeletePetCommand
return (created)

' Exec Method
CuddleCare -> DeletePetCommand : exec(args : String)
activate DeletePetCommand

' getPetName Method
DeletePetCommand -> DeletePetCommand : getPetName(args: String)
activate DeletePetCommand
return petName : String

' if input was invalid
alt petName == null ||petName.isEmpty()
    DeletePetCommand ->> Ui : printInvalidInputMessage(SYNTAX)
    activate Ui
    return
    DeletePetCommand --> CuddleCare

else else
    DeletePetCommand -> PetList : getPetByName(petName)
    activate PetList
    return pet: Pet

    ' if invalid pet
    alt pet == null
        DeletePetCommand --> CuddleCare : print "No Pet Found"

    else else
        DeletePetCommand -> PetList : deletePet(pet)
        activate PetList
        return !isDeleted : boolean

        ' if some error in deleting the pet
        alt !isDeleted
            DeletePetCommand --> CuddleCare : print "Could not delete"

        else else

        end


    end

end
' happy path
            return print "Pet Deleted"

@enduml
