@startuml
skinparam classAttributeIconSize 0
title DeletePetCommand Class Diagram

interface Command {
    + exec(args: String) : void
}

class DeletePetCommand {
    - {static} LOGGER: Logger
    - {static} SYNTAX : String
    + DeletePetCommand(pets: PetList)
    + exec(args: String) : void
    - getPetName(input: String) : String
}

class PetList {
    + deletePet(petToDelete: Pet) : boolean
}

class Pet {

}

Command <|.. DeletePetCommand

DeletePetCommand --o "1" PetList : -pets >

PetList --> "*" Pet : has ArrayList >


DeletePetCommand -right[hidden]- PetList


@enduml