@startuml
title EditPetCommand Sequence Diagram
actor User
participant ":CuddleCare" as CuddleCare
participant ":Parser" as Parser
participant ":CommandWithArguments" as CWA
participant ":EditPetCommand" as EPC
participant ":PetList" as PetList
participant ":Pet" as Pet
participant ":Ui" as Ui

User -> CuddleCare : edit-pet n/Milo a/4
activate CuddleCare
CuddleCare -> Parser : parse(...)
activate Parser
Parser --> CuddleCare : CWA(EPC,"n/Milo a/4")
deactivate Parser

CuddleCare -> CWA : exec()
activate CWA
CWA -> EPC : exec(...)
activate EPC
EPC -> PetList : getPetByName("Milo")
activate PetList
PetList --> EPC : Pet/null
deactivate PetList

alt not found
  EPC --> CWA : "Pet not found"
else found
  EPC -> Pet : setAge(4) [maybe setName/setSpecies]
  activate Pet
  Pet --> EPC : ok
  deactivate Pet
  EPC --> CWA : success
end
  EPC -> Ui : prints
deactivate EPC
CWA --> CuddleCare : return
deactivate CWA
deactivate CuddleCare
Ui --> User : prints

@enduml