@startuml
title ListPetsCommand Sequence Diagram
actor User
participant ":CuddleCare" as CuddleCare
participant ":Parser" as Parser
participant ":CommandWithArguments" as CWA
participant ":ListPetsCommand" as LPC
participant ":PetList" as PetList
participant "<<class>>\nUi" as Ui

User -> CuddleCare : "list pets"
activate CuddleCare
CuddleCare -> Parser : parse("list pets")
activate Parser
Parser --> CuddleCare : CWA(LPC,"")
deactivate Parser

CuddleCare -> CWA : exec()
activate CWA
CWA -> LPC : exec("")
activate LPC
LPC -> PetList : size()
activate PetList
PetList --> LPC : n
deactivate PetList

alt empty
  LPC -> Ui : print("No pets found.")
  activate Ui
  Ui --> LPC : displays message
  deactivate Ui
else non-empty
  LPC -> Ui : print("Here are your pets...")
  activate Ui
  Ui --> LPC : displays message
  deactivate Ui
end

LPC --> CWA : return
deactivate LPC
CWA --> CuddleCare : return
deactivate CWA
CuddleCare --> User : return
deactivate CuddleCare
@enduml
