@startuml
title ListPetsCommand Sequence Diagram
actor User
participant ":CuddleCare" as CuddleCare
participant ":Parser" as Parser
participant ":CommandWithArguments" as CWA
participant ":ListPetsCommand" as LPC
participant ":PetList" as PetList
participant ":Ui" as Ui

User -> CuddleCare : "list pets"
activate CuddleCare
CuddleCare -> Parser : parse("list pets")
activate Parser
Parser --> CuddleCare : CWA(LPC,"")
deactivate Parser

CuddleCare -> CWA : exec()
activate CWA
CWA -> LPC : exec("")
activate LPC
LPC -> PetList : size()
activate PetList
PetList --> LPC : n
deactivate PetList
alt empty
  LPC --> CWA : "No pets found."
else non-empty
  LPC --> CWA : "Here are your pets..."
end
  LPC --> Ui : prints
deactivate LPC
CWA --> CuddleCare : return
deactivate CWA
Ui --> User : prints
deactivate CuddleCare
@enduml