@startuml
title MarkTreatmentCommand Sequence Diagram
actor User
participant ":CuddleCare" as CuddleCare
participant ":Parser" as Parser
participant ":CommandWithArguments" as CWA
participant ":MarkTreatmentCommand" as MTC
participant ":PetList" as PetList
participant ":Pet" as Pet
participant "<<class>>\nUi" as Ui

User -> CuddleCare : mark n/Milo i/2
activate CuddleCare
CuddleCare -> Parser : parse(...)
activate Parser
Parser --> CuddleCare : CWA(MTC,"n/Milo i/2")
deactivate Parser

CuddleCare -> CWA : exec()
activate CWA
CWA -> MTC : exec(...)
activate MTC
MTC -> PetList : getPetByName("Milo")
activate PetList
PetList --> MTC : Pet/null
deactivate PetList

alt not found
  MTC -> Ui : print("No such pet")
  activate Ui
  Ui --> User : displays message
  Ui --> MTC : done
  deactivate Ui
else found
  MTC -> Pet : getTreatments()[index-1].setCompleted(true)
  activate Pet
  Pet --> MTC : ok
  deactivate Pet
  MTC -> Ui : print("Marked.")
  activate Ui
  Ui --> User : displays confirmation
  Ui --> MTC : done
  deactivate Ui
end

MTC --> CWA : return
deactivate MTC
CWA --> CuddleCare : return
deactivate CWA
deactivate CuddleCare
@enduml
