@startuml
title MarkTreatmentCommand Sequence Diagram
actor User
participant ":CuddleCare" as CuddleCare
participant ":Parser" as Parser
participant ":CommandWithArguments" as CWA
participant ":MarkTreatmentCommand" as MTC
participant ":PetList" as PetList
participant ":Pet" as Pet
participant ":Ui" as Ui

User -> CuddleCare : mark n/Milo i/2
activate CuddleCare
CuddleCare -> Parser : parse(...)
activate Parser
Parser --> CuddleCare : CWA(MTC,"n/Milo i/2")
deactivate Parser

CuddleCare -> CWA : exec()
activate CWA
CWA -> MTC : exec(...)
activate MTC
MTC -> PetList : getPetByName("Milo")
activate PetList
PetList --> MTC : Pet/null
deactivate PetList

alt not found
  MTC --> CWA : "No such pet"
else found
  MTC -> Pet : getTreatments()[index-1].setCompleted(true)
  activate Pet
  Pet --> MTC : ok
  deactivate Pet
  MTC --> CWA : "Marked."
end
  MTC -> Ui : prints
deactivate MTC
activate Ui
CWA --> CuddleCare : return
deactivate CWA
deactivate CuddleCare
Ui --> User : prints
deactivate Ui
@enduml